// <auto-generated />
using System;
using GestionEmpresarial.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEmpresarial.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260722231312_EnumGradoConocimiento")]
    partial class EnumGradoConocimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_asignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_finalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Conocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area_Conocimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo_Conocimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Conocimientos");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_proyecto")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTecnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Tecnico_Conocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConocimientoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Tecnico_Conocimientos");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Asignacion", b =>
                {
                    b.HasOne("GestionEmpresarial.Shared.Entities.Proyecto", "Proyecto")
                        .WithMany("Asignacion")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmpresarial.Shared.Entities.Tecnico", "Tecnico")
                        .WithMany("Asignacion")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Proyecto", b =>
                {
                    b.HasOne("GestionEmpresarial.Shared.Entities.Cliente", "Cliente")
                        .WithMany("Proyecto")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Tecnico", b =>
                {
                    b.HasOne("GestionEmpresarial.Shared.Entities.Categoria", "Categoria")
                        .WithMany("Tecnico")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmpresarial.Shared.Entities.Empresa", "Empresa")
                        .WithMany("Tecnico")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Tecnico_Conocimiento", b =>
                {
                    b.HasOne("GestionEmpresarial.Shared.Entities.Conocimiento", "Conocimiento")
                        .WithMany("Tecnico_Conocimiento")
                        .HasForeignKey("ConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmpresarial.Shared.Entities.Tecnico", "Tecnico")
                        .WithMany("Tecnico_Conocimiento")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conocimiento");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Categoria", b =>
                {
                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Cliente", b =>
                {
                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Conocimiento", b =>
                {
                    b.Navigation("Tecnico_Conocimiento");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Empresa", b =>
                {
                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Proyecto", b =>
                {
                    b.Navigation("Asignacion");
                });

            modelBuilder.Entity("GestionEmpresarial.Shared.Entities.Tecnico", b =>
                {
                    b.Navigation("Asignacion");

                    b.Navigation("Tecnico_Conocimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
